# The URL the site will be built for
base_url = "https://example.com"
title = "recept är gött"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

default_language = "sv" 

[extra]
# Put all your custom variables here
